# Generated by Django 5.2 on 2025-11-21 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_number', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_image', models.ImageField(upload_to='Employee_images/')),
                ('name', models.CharField(max_length=100)),
                ('id_image', models.ImageField(upload_to='ID_images')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('mobile_number', models.CharField(max_length=100)),
                ('assignment', models.TextField(default=True, max_length=200)),
            ],
        ),
    ]
