# Generated by Django 5.2 on 2025-11-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASHBOARD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policydocs',
            name='document',
        ),
        migrations.AddField(
            model_name='policydocs',
            name='documents',
            field=models.FileField(default=True, upload_to='media/files/documents'),
        ),
    ]
