# Generated by Django 5.2 on 2025-11-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASHBOARD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
