# Generated by Django 5.2 on 2025-11-04 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DASHBOARD', '0002_remove_policydocs_document_policydocs_documents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PolicyDocs',
            new_name='PolicyDoc',
        ),
    ]
