# Generated by Django 5.2 on 2025-11-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASHBOARD', '0002_employee_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('farm_number', models.IntegerField(primary_key=True, serialize=False)),
                ('farm_image', models.ImageField(upload_to='Farm_images/')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
