# Generated by Django 5.2 on 2025-11-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASHBOARD', '0003_rename_policydocs_policydoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='policydoc',
            name='images',
            field=models.ImageField(default=True, upload_to='media/files/images'),
        ),
    ]
