# Generated by Django 5.2 on 2025-11-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASHBOARD', '0003_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='description',
            field=models.TextField(default=True, max_length=1000),
        ),
    ]
