# Generated by Django 5.2 on 2025-11-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASHBOARD', '0004_policydoc_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policydoc',
            name='documents',
            field=models.FileField(default=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='policydoc',
            name='images',
            field=models.ImageField(default=True, upload_to='images'),
        ),
    ]
