# Generated by Django 5.2 on 2025-11-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASHBOARD', '0004_farm_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_image',
            field=models.ImageField(blank=True, null=True, upload_to='Employee_images/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_image',
            field=models.ImageField(blank=True, null=True, upload_to='ID_images'),
        ),
    ]
